### ISSUE TITLE
Android RTL

### ISSUE THREAD

**Issue by mdaldoukhi** [ahmedrowaihi/react-native-i18n-storage#6]
السلام عليكم ورحمة الله وبركاته

First of all, thanks for your effort by give us a simple way to have library handle the languages. 

I just notice that, android will not change to RTL because we need to add the below notes:

- Need to add 2 lines to in MainApplication.java:
-- I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance(); 
-- sharedI18nUtilInstance.allowRTL(getApplicationContext(), true);

- import this line in MainApplication.java:
-- import com.facebook.react.modules.i18nmanager.I18nUtil;

- add this line to AndroidManifest.xml:
-- android:supportsRtl="true"

When I added these notes, android worked perfectly. 

Best regards,
mdaldoukhi

**Comment by ahmedrowaihi** [comment]
وعليكم السلام ورحمة الله وبركاته.
من فترة لم اواجه مشكلة مع الاندرويد او الـ IOS 

بالنسبة الى "allowRTL" فالمكتبة تقوم بذلك ويمكنك التحقق هنا في

السطر 62

https://github.com/ahmedrowaihi/react-native-i18n-storage/blob/main/android/src/main/java/com/i18nstorage/I18nStorageUtility.java


اما عن النقطه الاخيرة
AndroidManifest.xml: -- android:supportsRtl="true"
صحيح نسيت ان اذكر ذلك في وثيقة الاستخدام، سأضيف ذلك

شكرا جزيلا اسعدني اهتمامك بالمكتبة
